# Generated by Django 6.0.5 on 2026-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(to='books_authors_app.books'),
        ),
    ]
